name: Hello World

on:
  push:
    branches: [ main ]

jobs:
  say-hello:
    # ジョブ全体にifを指定することもできます。
    if: false # This job disabled
    runs-on: ubuntu-latest
    steps:
      - name: Create greeting file
        run: echo "Hello, World!" > greeting.txt

      - name: Upload artifact
        # ステップ単位でifを指定することもできます。
        if: false # This step disabled
        uses: actions/upload-artifact@v4
        with:
          name: greeting
          path: greeting.txt

  read-greeting:
    if: false # This job disabled
    needs: say-hello
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: greeting

      - name: Read Greeting
        run: cat greeting.txt
